// app/layout.tsx

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import Bottomheader from "./layouts/bottomheader";
import Topheader from "./layouts/topheader";
import Header from "./layouts/header";
import Sidebar from "./layouts/siderbar";
import Footer from "./layouts/footer";
import { getCategories } from "./api/sidebar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Mark layout async so we can await categories
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const categories = await getCategories() || [];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Sidebar categories={categories} />
            <Topheader />
            <Header />
            <Bottomheader />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
